name: CMake Firmware

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive # CRITICAL for guitar mods

    - name: Checkout pico sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        submodules: true

    - name: Install ARM Toolchain & Build Tools
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential ninja-build

    - name: Configure and Build
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
      run: |
        mkdir build
        cd build
        cmake -G Ninja .. # Using Ninja avoids "Unix Makefiles" errors
        ninja

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: pico_rectangle_guitar_firmware
        path: build/*.uf2 # Grabs all versions (Standard, ULT, etc.)
