name: CMake Firmware

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive # Gets the necessary Joybus/Guitar libraries

    - name: Checkout pico sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        submodules: true
        
    - name: Install Toolchain and Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential cmake ninja-build

    
    - name: Configure and Build
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja

    - name: Upload Standard Firmware
      uses: actions/upload-artifact@v4
      with:
        name: pico_rectangle_standard
        path: build/pico_rectangle.uf2

    - name: Upload Ult 2IP SOCD
      uses: actions/upload-artifact@v4
      with:
        name: pico_rectangle_ult_2ip
        path: build/pico_rectangle_ULT_2IP_WITH_REAC.uf2
        if-no-files-found: warn

    - name: Upload Ult Neutral SOCD
      uses: actions/upload-artifact@v4
      with:
        name: pico_rectangle_ult_neutral
        path: build/pico_rectangle_ULT_NEUTRAL.uf2
        if-no-files-found: warn

    - name: Upload SG Guitar Firmware
      uses: actions/upload-artifact@v4
      with:
        name: pico_rectangle_sg_standard
        path: build/pico_rectangle_sg.uf2
        if-no-files-found: warn

    - name: Upload SG Guitar Ult 2IP SOCD
      uses: actions/upload-artifact@v4
      with:
        name: pico_rectangle_sg_ult_2ip
        path: build/pico_rectangle_sg_ULT_2IP_WITH_REAC.uf2
        if-no-files-found: warn

    - name: Upload SG Guitar Ult Neutral SOCD
      uses: actions/upload-artifact@v4
      with:
        name: pico_rectangle_sg_ult_neutral
        path: build/pico_rectangle_sg_ULT_NEUTRAL.uf2
        if-no-files-found: warn
